language: python
dist: xenial
python: 3.7
install:
  - pip install -r requirements.txt
stages:
  - test
jobs:
  include:
    - stage: test
      script:
        - cd $HOME && wget http://apachemirror.wuchna.com/spark/spark-3.0.1/spark-3.0.1-bin-hadoop2.7.tgz && tar -xzf spark-3.0.1-bin-hadoop2.7.tgz
        - cd $TRAVIS_BUILD_DIR
        - export SPARK_HOME=$HOME/spark-3.0.1-bin-hadoop2.7
        - export PYTHON_PYSPARK=python
        - export PATH0=$SPARK_HOME/bin:$PATH
        - coverage run test.py
        - coverage xml
        - sonar-scanner

addons:
  sonarcloud:
    organization: snemmani

